/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_axonops_libre2_jni_RE2NativeJNI */

#ifndef _Included_com_axonops_libre2_jni_RE2NativeJNI
#define _Included_com_axonops_libre2_jni_RE2NativeJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    compile
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_compile
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    freePattern
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_freePattern
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    fullMatch
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_fullMatch
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    partialMatch
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_partialMatch
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_getError
  (JNIEnv *, jclass);

/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    getPattern
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_getPattern
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    numCapturingGroups
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_numCapturingGroups
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    patternOk
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_patternOk
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_axonops_libre2_jni_RE2NativeJNI
 * Method:    patternMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_axonops_libre2_jni_RE2NativeJNI_patternMemory
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
